Renaming blacklist/whitelist aligned with android-components #7557
mozilla-extensions/webcompat-addon pull request #195
Opened 2020-10-23 18:28 UTC by VMadalin

### Description 
https://github.com/mozilla-mobile/android-components/issues/7557

### Overview
I follow exactly the iOS changes on this PR: https://github.com/mozilla-mobile/firefox-ios/pull/6783/files

2020-10-23 20:33 UTC, denschub requested changes

2020-10-23 20:33 UTC, denschub commented on src/experiment-apis/matchPatterns.json
> +            "description": "Array of string URL patterns to safelist",
As I said in https://github.com/mozilla-mobile/android-components/pull/8642#discussion_r505816513, there is no security-context here, so "safelist" is actually inaccurate. "allowlist" or simply rewording "Array of string URL patterns to match" is much more accurate here.

2020-10-24 12:47 UTC, VMadalin commented on src/experiment-apis/matchPatterns.json
> +            "description": "Array of string URL patterns to safelist",
```suggestion
            "description": "Array of string URL patterns to match",
```

2020-10-24 13:59 UTC, denschub approved these changes

2020-10-24 13:59 UTC, merged